sonar.projectKey=andre749_laboratorio_8_ing_software
sonar.organization=andre749

sonar.sources=.
sonar.exclusions=.venv/**,tests/**,**/__pycache__/**,*.pyc

sonar.tests=.
sonar.test.inclusions=**/tests/**,**test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
